DROP TABLE IF EXISTS customer_shopping_behavior;

CREATE TABLE customer_shopping_behavior (
    customer_id INTEGER,
    age INTEGER,
    gender VARCHAR(20),
    item_purchased VARCHAR(100),
    category VARCHAR(50),
    purchase_amount_usd INTEGER,
    location VARCHAR(100),
    size VARCHAR(20),
    color VARCHAR(50),
    season VARCHAR(20),
    review_rating NUMERIC(4,2),
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    previous_purchases INTEGER,
    payment_method VARCHAR(50),
    frequency_of_purchases VARCHAR(50),
    age_group VARCHAR(20),
    purchase_frequency_days NUMERIC(10,2)
);

select * from customer_shopping_behavior 
limit 10;

--what is the total revenue generated by male vs female customer 
select gender,sum(purchase_amount_usd) from customer_shopping_behavior
group by gender;

--which customer used a discount but still spent ore than the average purchase amount
select avg(purchase_amount_usd) from customer_shopping_behavior;
select customer_id,purchase_amount_usd from customer_shopping_behavior
where lower(discount_applied) = 'yes' and purchase_amount_usd>=(select avg(purchase_amount_usd) from 
customer_shopping_behavior);

--which are the top 5 product with the highest review rating?
select item_purchased, Round(avg(review_rating),2) as "average product rating " from customer_shopping_behavior
group by item_purchased
order by avg (review_rating) desc
limit 5;

--compare the average purchase amounts between standard and express shipping 
select shipping_type, Round(avg(purchase_amount_usd),2) from customer_shopping_behavior
group by shipping_type having shipping_type in ('Express','Standard');

--do subscribed customers spend more? compare average spend and total revenue between subscribed and unsubscribed customer
select subscription_status,
avg(purchase_amount_usd),
sum(purchase_amount_usd),
count(customer_id) as total_customer
from customer_shopping_behavior
group by subscription_status;

--which 5 products have the highest percentage of purchases with discounts applied 
select item_purchased as Product,
count(item_purchased),
Round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;

--segment customers into new, returning and loyal based on their total
--no. of previous purchases, and show the count of each segment 
--(THIS IS A QUESTION OF CUSTOMER SEGMENTATION)
with customer_type as(
select customer_id, previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else'Loyal' end as customer_segment 
from customer_shopping_behavior
)
select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment;

--what are the top 3 most purchases products within each category 
with item_counts as(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_shopping_behavior
group by category, item_purchased
)
select item_rank,category, item_purchased,total_orders
from item_counts
where item_rank <= 3;

--are customer who are repeat buyers (more than 5 purchases) also likely to subscribe 
select subscription_status , count(customer_id)as repeat_buyers from customer_shopping_behavior
where previous_purchases>5
group by subscription_status ;

--what is the revenue contribution of each age group
select age_group,sum(purchase_amount_usd)as total_revenue from customer_shopping_behavior
group by age_group;